### ISSUE TITLE
Emojis autocompletion list position

### ISSUE THREAD

**Issue by nemolovich** [heartless-gaming/ezChat#15]
Get the autocompletion of emojis at the top of the text field:

```css
ul.dropdown-menu.scrollable-menu {
    bottom: 0;
    position: absolute;
    /* <Some displays> */
    background: rgba(27, 27, 27, 0.85);
    padding: 5px;
    margin-bottom: 15px;
    /* </Some displays> */
}
```
